# Generated by Django 5.1.2 on 2024-11-07 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client'),
        ),
    ]
